### ISSUE TITLE
Bamboleo

### ISSUE THREAD

**Issue by LorenaGadea** [LorenaGadea/Ticketing#2]
La desproporcionada cantidad de commits y mierdas se deben a que estoy enseñando a usar git a esta mujer y aprendiendo yo así que he hecho un poco de todo para elaborar una 'guía' en este nuestro repositorio conejillo de indias.

**Comment by JavierMendezGomez** [comment]
Recibido.
Procedo a dar carpetazo a este asunto puramente comunicativo.
