### ISSUE TITLE
Necesidad o no de un diagrama de  las tablas en la base de datos

### ISSUE THREAD

**Issue by JavierMendezGomez** [LorenaGadea/Ticketing#3]
¿Vendría bien tener un esquemas de las tablas con sus relaciones que se suban a la carpeta misma de la base de datos?
Son muy pocas, pero por practicar y recordar cómo iba PlantUML quizá merezca la pena.

**Comment by LorenaGadea** [comment]
Bueno, es un poco lo de siempre que tenemos más que aprendido, pero por qué no. Documentar siempre es virtuoso.

**Comment by JavierMendezGomez** [comment]
Subido el esquema, cierro esto
